export interface StaticChampion {
  season: string;
  driverId: string;
  givenName: string;
  familyName: string;
  constructorId: string;
  constructorName: string;
  points: string;
}

export const F1_CHAMPIONS: StaticChampion[] = [
  { season: "1950", driverId: "farina",       givenName: "Giuseppe",  familyName: "Farina",     constructorId: "alfa",        constructorName: "Alfa Romeo",  points: "30" },
  { season: "1951", driverId: "fangio",        givenName: "Juan",      familyName: "Fangio",     constructorId: "alfa",        constructorName: "Alfa Romeo",  points: "31" },
  { season: "1952", driverId: "ascari",        givenName: "Alberto",   familyName: "Ascari",     constructorId: "ferrari",     constructorName: "Ferrari",     points: "36" },
  { season: "1953", driverId: "ascari",        givenName: "Alberto",   familyName: "Ascari",     constructorId: "ferrari",     constructorName: "Ferrari",     points: "34.5" },
  { season: "1954", driverId: "fangio",        givenName: "Juan",      familyName: "Fangio",     constructorId: "maserati",    constructorName: "Maserati",    points: "42" },
  { season: "1955", driverId: "fangio",        givenName: "Juan",      familyName: "Fangio",     constructorId: "mercedes",    constructorName: "Mercedes",    points: "40" },
  { season: "1956", driverId: "fangio",        givenName: "Juan",      familyName: "Fangio",     constructorId: "ferrari",     constructorName: "Ferrari",     points: "30" },
  { season: "1957", driverId: "fangio",        givenName: "Juan",      familyName: "Fangio",     constructorId: "maserati",    constructorName: "Maserati",    points: "40" },
  { season: "1958", driverId: "hawthorn",      givenName: "Mike",      familyName: "Hawthorn",   constructorId: "ferrari",     constructorName: "Ferrari",     points: "42" },
  { season: "1959", driverId: "brabham",       givenName: "Jack",      familyName: "Brabham",    constructorId: "cooper",      constructorName: "Cooper",      points: "31" },
  { season: "1960", driverId: "brabham",       givenName: "Jack",      familyName: "Brabham",    constructorId: "cooper",      constructorName: "Cooper",      points: "43" },
  { season: "1961", driverId: "phil_hill",     givenName: "Phil",      familyName: "Hill",       constructorId: "ferrari",     constructorName: "Ferrari",     points: "34" },
  { season: "1962", driverId: "graham_hill",   givenName: "Graham",    familyName: "Hill",       constructorId: "brm",         constructorName: "BRM",         points: "42" },
  { season: "1963", driverId: "clark",         givenName: "Jim",       familyName: "Clark",      constructorId: "lotus",       constructorName: "Lotus-Climax",points: "54" },
  { season: "1964", driverId: "surtees",       givenName: "John",      familyName: "Surtees",    constructorId: "ferrari",     constructorName: "Ferrari",     points: "40" },
  { season: "1965", driverId: "clark",         givenName: "Jim",       familyName: "Clark",      constructorId: "lotus",       constructorName: "Lotus-Climax",points: "54" },
  { season: "1966", driverId: "brabham",       givenName: "Jack",      familyName: "Brabham",    constructorId: "brabham",     constructorName: "Brabham",     points: "42" },
  { season: "1967", driverId: "hulme",         givenName: "Denny",     familyName: "Hulme",      constructorId: "brabham",     constructorName: "Brabham",     points: "51" },
  { season: "1968", driverId: "graham_hill",   givenName: "Graham",    familyName: "Hill",       constructorId: "lotus",       constructorName: "Lotus-Ford",  points: "48" },
  { season: "1969", driverId: "stewart",       givenName: "Jackie",    familyName: "Stewart",    constructorId: "matra",       constructorName: "Matra",       points: "63" },
  { season: "1970", driverId: "rindt",         givenName: "Jochen",    familyName: "Rindt",      constructorId: "lotus",       constructorName: "Lotus-Ford",  points: "45" },
  { season: "1971", driverId: "stewart",       givenName: "Jackie",    familyName: "Stewart",    constructorId: "tyrrell",     constructorName: "Tyrrell",     points: "62" },
  { season: "1972", driverId: "fittipaldi",    givenName: "Emerson",   familyName: "Fittipaldi", constructorId: "lotus",       constructorName: "Lotus-Ford",  points: "61" },
  { season: "1973", driverId: "stewart",       givenName: "Jackie",    familyName: "Stewart",    constructorId: "tyrrell",     constructorName: "Tyrrell",     points: "71" },
  { season: "1974", driverId: "fittipaldi",    givenName: "Emerson",   familyName: "Fittipaldi", constructorId: "mclaren",     constructorName: "McLaren",     points: "55" },
  { season: "1975", driverId: "lauda",         givenName: "Niki",      familyName: "Lauda",      constructorId: "ferrari",     constructorName: "Ferrari",     points: "64.5" },
  { season: "1976", driverId: "hunt",          givenName: "James",     familyName: "Hunt",       constructorId: "mclaren",     constructorName: "McLaren",     points: "69" },
  { season: "1977", driverId: "lauda",         givenName: "Niki",      familyName: "Lauda",      constructorId: "ferrari",     constructorName: "Ferrari",     points: "72" },
  { season: "1978", driverId: "andretti",      givenName: "Mario",     familyName: "Andretti",   constructorId: "lotus",       constructorName: "Lotus-Ford",  points: "64" },
  { season: "1979", driverId: "scheckter",     givenName: "Jody",      familyName: "Scheckter",  constructorId: "ferrari",     constructorName: "Ferrari",     points: "51" },
  { season: "1980", driverId: "jones",         givenName: "Alan",      familyName: "Jones",      constructorId: "williams",    constructorName: "Williams",    points: "67" },
  { season: "1981", driverId: "piquet",        givenName: "Nelson",    familyName: "Piquet",     constructorId: "brabham",     constructorName: "Brabham",     points: "50" },
  { season: "1982", driverId: "keke_rosberg",  givenName: "Keke",      familyName: "Rosberg",    constructorId: "williams",    constructorName: "Williams",    points: "44" },
  { season: "1983", driverId: "piquet",        givenName: "Nelson",    familyName: "Piquet",     constructorId: "brabham",     constructorName: "Brabham",     points: "59" },
  { season: "1984", driverId: "lauda",         givenName: "Niki",      familyName: "Lauda",      constructorId: "mclaren",     constructorName: "McLaren",     points: "72" },
  { season: "1985", driverId: "prost",         givenName: "Alain",     familyName: "Prost",      constructorId: "mclaren",     constructorName: "McLaren",     points: "73" },
  { season: "1986", driverId: "prost",         givenName: "Alain",     familyName: "Prost",      constructorId: "mclaren",     constructorName: "McLaren",     points: "72" },
  { season: "1987", driverId: "piquet",        givenName: "Nelson",    familyName: "Piquet",     constructorId: "williams",    constructorName: "Williams",    points: "73" },
  { season: "1988", driverId: "senna",         givenName: "Ayrton",    familyName: "Senna",      constructorId: "mclaren",     constructorName: "McLaren",     points: "90" },
  { season: "1989", driverId: "prost",         givenName: "Alain",     familyName: "Prost",      constructorId: "mclaren",     constructorName: "McLaren",     points: "76" },
  { season: "1990", driverId: "senna",         givenName: "Ayrton",    familyName: "Senna",      constructorId: "mclaren",     constructorName: "McLaren",     points: "78" },
  { season: "1991", driverId: "senna",         givenName: "Ayrton",    familyName: "Senna",      constructorId: "mclaren",     constructorName: "McLaren",     points: "96" },
  { season: "1992", driverId: "mansell",       givenName: "Nigel",     familyName: "Mansell",    constructorId: "williams",    constructorName: "Williams",    points: "108" },
  { season: "1993", driverId: "prost",         givenName: "Alain",     familyName: "Prost",      constructorId: "williams",    constructorName: "Williams",    points: "99" },
  { season: "1994", driverId: "schumacher",    givenName: "Michael",   familyName: "Schumacher", constructorId: "benetton",    constructorName: "Benetton",    points: "92" },
  { season: "1995", driverId: "schumacher",    givenName: "Michael",   familyName: "Schumacher", constructorId: "benetton",    constructorName: "Benetton",    points: "102" },
  { season: "1996", driverId: "damon_hill",    givenName: "Damon",     familyName: "Hill",       constructorId: "williams",    constructorName: "Williams",    points: "97" },
  { season: "1997", driverId: "villeneuve",    givenName: "Jacques",   familyName: "Villeneuve", constructorId: "williams",    constructorName: "Williams",    points: "81" },
  { season: "1998", driverId: "hakkinen",      givenName: "Mika",      familyName: "Häkkinen",   constructorId: "mclaren",     constructorName: "McLaren",     points: "100" },
  { season: "1999", driverId: "hakkinen",      givenName: "Mika",      familyName: "Häkkinen",   constructorId: "mclaren",     constructorName: "McLaren",     points: "76" },
  { season: "2000", driverId: "schumacher",    givenName: "Michael",   familyName: "Schumacher", constructorId: "ferrari",     constructorName: "Ferrari",     points: "108" },
  { season: "2001", driverId: "schumacher",    givenName: "Michael",   familyName: "Schumacher", constructorId: "ferrari",     constructorName: "Ferrari",     points: "123" },
  { season: "2002", driverId: "schumacher",    givenName: "Michael",   familyName: "Schumacher", constructorId: "ferrari",     constructorName: "Ferrari",     points: "144" },
  { season: "2003", driverId: "schumacher",    givenName: "Michael",   familyName: "Schumacher", constructorId: "ferrari",     constructorName: "Ferrari",     points: "93" },
  { season: "2004", driverId: "schumacher",    givenName: "Michael",   familyName: "Schumacher", constructorId: "ferrari",     constructorName: "Ferrari",     points: "148" },
  { season: "2005", driverId: "alonso",        givenName: "Fernando",  familyName: "Alonso",     constructorId: "renault",     constructorName: "Renault",     points: "133" },
  { season: "2006", driverId: "alonso",        givenName: "Fernando",  familyName: "Alonso",     constructorId: "renault",     constructorName: "Renault",     points: "134" },
  { season: "2007", driverId: "raikkonen",     givenName: "Kimi",      familyName: "Räikkönen",  constructorId: "ferrari",     constructorName: "Ferrari",     points: "110" },
  { season: "2008", driverId: "hamilton",      givenName: "Lewis",     familyName: "Hamilton",   constructorId: "mclaren",     constructorName: "McLaren",     points: "98" },
  { season: "2009", driverId: "button",        givenName: "Jenson",    familyName: "Button",     constructorId: "brawn",       constructorName: "Brawn",       points: "95" },
  { season: "2010", driverId: "vettel",        givenName: "Sebastian", familyName: "Vettel",     constructorId: "red_bull",    constructorName: "Red Bull",    points: "256" },
  { season: "2011", driverId: "vettel",        givenName: "Sebastian", familyName: "Vettel",     constructorId: "red_bull",    constructorName: "Red Bull",    points: "392" },
  { season: "2012", driverId: "vettel",        givenName: "Sebastian", familyName: "Vettel",     constructorId: "red_bull",    constructorName: "Red Bull",    points: "281" },
  { season: "2013", driverId: "vettel",        givenName: "Sebastian", familyName: "Vettel",     constructorId: "red_bull",    constructorName: "Red Bull",    points: "397" },
  { season: "2014", driverId: "hamilton",      givenName: "Lewis",     familyName: "Hamilton",   constructorId: "mercedes",    constructorName: "Mercedes",    points: "384" },
  { season: "2015", driverId: "hamilton",      givenName: "Lewis",     familyName: "Hamilton",   constructorId: "mercedes",    constructorName: "Mercedes",    points: "381" },
  { season: "2016", driverId: "rosberg",       givenName: "Nico",      familyName: "Rosberg",    constructorId: "mercedes",    constructorName: "Mercedes",    points: "385" },
  { season: "2017", driverId: "hamilton",      givenName: "Lewis",     familyName: "Hamilton",   constructorId: "mercedes",    constructorName: "Mercedes",    points: "363" },
  { season: "2018", driverId: "hamilton",      givenName: "Lewis",     familyName: "Hamilton",   constructorId: "mercedes",    constructorName: "Mercedes",    points: "408" },
  { season: "2019", driverId: "hamilton",      givenName: "Lewis",     familyName: "Hamilton",   constructorId: "mercedes",    constructorName: "Mercedes",    points: "413" },
  { season: "2020", driverId: "hamilton",      givenName: "Lewis",     familyName: "Hamilton",   constructorId: "mercedes",    constructorName: "Mercedes",    points: "347" },
  { season: "2021", driverId: "max_verstappen",givenName: "Max",       familyName: "Verstappen", constructorId: "red_bull",    constructorName: "Red Bull",    points: "395.5" },
  { season: "2022", driverId: "max_verstappen",givenName: "Max",       familyName: "Verstappen", constructorId: "red_bull",    constructorName: "Red Bull",    points: "454" },
  { season: "2023", driverId: "max_verstappen",givenName: "Max",       familyName: "Verstappen", constructorId: "red_bull",    constructorName: "Red Bull",    points: "575" },
  { season: "2024", driverId: "max_verstappen",givenName: "Max",       familyName: "Verstappen", constructorId: "red_bull",    constructorName: "Red Bull",    points: "437" },
];
